Fix common_translation_update
Use "git rm -f" to force removal. We might have files that were changed by
the previous steps and then "git rm" will fail with:
$ git rm heat/locale/fr/LC_MESSAGES/heat-log-warning.po
error: 'heat/locale/fr/LC_MESSAGES/heat-log-warning.po' has changes
 staged in the index
| (use --cached to keep the file, or -f to force removal)

This change is needed to fix propose_translation_update.sh for a few
repositories including heat.

Change-Id: Ia5887a0442a25d6bd66351f266cb392cb46ca4d5