Remove unneeded noop-jobs from airship
All airship repos have in-tree check and gate queues with jobs, so we
can remove the noop-jobs template for them.

Change-Id: Ia84150d41e5bd2744b5f469c5146d0ab978ba1ea
Exception: airship-berth, keep noop for it.