Fix invalid spacing in yaml file
Zuul barfed reading the layout file because of the extra space.

Error from zuul:

  yaml.scanner.ScannerError: mapping values are not allowed here
    in "etc/zuul/layout/layout.yaml", line 22, column 28

Change-Id: Icaf2d5aa5904907c441d377ccafdd107f4d9d77e