Check for valid entries in gerrit/projects.yaml
Rename check_upstream_url_scheme.py to check_valid_gerrit_projects.py
and extend the check so that:
* It shows all errors, not only the first one
* It checks that the keywords are valid

This was triggered by seen twice in a week the keyword "description"
misspelled.

Script now outputs in error case:
Error: Upstream URLs should use a scheme in ['https://', 'http://', 'git://'],
 found git@://github.com/emonty/cookiecutter-openstack.git in
 openstack-dev/cookiecutter
Error: Unknown keyword 'decription' in project stackforge/ec2-driver
Found 2 error(s) in /tmp/projects.yaml

Also add the usual license header.

Change-Id: I334dcadc6fd4472fb28d379aec317c1a16dee2e2