Fix release-id fetching for release job
With a recent patch a new release job error came up [1]:
when fetching the release-id from the series_status.yaml the yaml
parser resolves the new names (eg: 2023.1) as float, so we have to
convert it to string to be able to concatenate it to 'stable/' string.

[1]
File "/home/zuul/scripts/release-tools/process_release_requests.py", line 116, in get_branch
branch = "stable/" + series.get("release-id", series_name)
TypeError: can only concatenate str (not "float") to str

Change-Id: I4e317919292d7481b2ffd15b68473fff5b4b9aaf